Update index.html file
Jawad-Nazari/Hello-Microverse pull request #2
Opened 2023-02-15 12:34 UTC by Jawad-Nazari

I have changed header of the index.html file.

2023-02-15 13:43 UTC, zieeco requested changes
Hi @Jawad-Nazari 


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice one setting up the Hello Microverse Project. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 13:43 UTC, zieeco commented on index.html
### NOTE: THE BELOW CHANGE IS NOT RELATED TO THIS INLINE COMMENT. CHECK THE REVIEW COMMENT CLOSELY:


#### :point_right:  PR TITLE AND DESCRIPTION

*PR's title and description*
![Screenshot from 2023-02-15 13-38-59](https://user-images.githubusercontent.com/59397159/219031518-49496c10-bc40-462b-b238-66275a00382f.png)


- [ ] Your PR's title is looking good, however, let's improve on it. Kindly update to either `Hello Microverse`, `Greeting`,, etc. as this is more descriptive you've not only made an update to the index.html file, you've added other files too.
- [ ] Let's also update the PR's description as the content is still not very descriptive. you can see the suggestion below:


```

*In this PR, I did the following:*

- Added the `index.html` file.
- Added the `style.css` file.
- Added the linters file.
- Added the `test.md` file to the `.gitignore` file.
- Ensured there was no linter error
- Documented the project in a professional way.

```

---

## :point_right:  README FILE
### :point_right: PLACEHOLDER TEXT

- [ ] Please, let's kindly remove the text seen in these images as these texts are placeholder text to guide on how to add and update the contents of different sections in the readme file to make the readme more professional.. 

![Screenshot from 2023-02-15 13-51-59](https://user-images.githubusercontent.com/59397159/219032865-c72d9461-e9e3-41ab-8316-c8b4a9bb1c04.png)
![Screenshot from 2023-02-15 13-51-38](https://user-images.githubusercontent.com/59397159/219032874-e8a54fa7-9195-4e04-90e5-d8a92dfe94f0.png)
![Screenshot from 2023-02-15 13-51-28](https://user-images.githubusercontent.com/59397159/219032876-9dcdef89-1d14-41a9-9043-e29bc60dbfc4.png)
![Screenshot from 2023-02-15 13-51-19](https://user-images.githubusercontent.com/59397159/219032878-3ed54a16-1eec-4910-98e7-46c22d91baa2.png)
![Screenshot from 2023-02-15 13-51-11](https://user-images.githubusercontent.com/59397159/219032881-e9a85dc1-05f5-4fa6-8409-992613066037.png)
![Screenshot from 2023-02-15 13-51-03](https://user-images.githubusercontent.com/59397159/219032883-b08e0130-46d3-46bc-be21-f18ad06b3c18.png)
![Screenshot from 2023-02-15 13-50-33](https://user-images.githubusercontent.com/59397159/219032888-07d00a76-1aea-41f3-a7d2-f1b459f7ce1c.png)
![Screenshot from 2023-02-15 13-50-19](https://user-images.githubusercontent.com/59397159/219032894-082f6a87-fd64-46ed-ba54-89abeea2a12b.png)

- [ ] Let's kindly remove this optional section of the readme file, as it's optional, except if you want to add some questions and answers concerning the project, otherwise, let's remove them


![Screenshot from 2023-02-15 13-55-58](https://user-images.githubusercontent.com/59397159/219033741-5c50a758-4063-476a-8b85-9390dd0621da.png)

---

#### :point_right:  ACKNOWLEDGEMENT

- [ ] Let's update the text to `I would like to thank Microverse for setting up this project for student`

#### :point_right: Show your support
- [ ] Let's update the text to `If you like this project, give it a star ` :star: 

#### :point_right:  FUTURE FEATURES
- For this section, you can add a summary of its features:
- [ ] Setting Up A Professional Github Repository.

#### :point_right:  REMOVE THE SECOND ADDED AUTHOR
- [ ] Please, kindly remove the second author added as you've worked on this project alone.

#### :point_right:  REMOVE UNUSED SECTIONS
- [ ] Please, let's kindly remove these unused sections from the readme as you've not used them by adding the appropriate contents to make the readme more professional:

![Screenshot from 2023-02-15 14-14-09](https://user-images.githubusercontent.com/59397159/219037648-80729ab3-5d18-4caf-b3ee-8310267a9998.png)
![Screenshot from 2023-02-15 14-13-58](https://user-images.githubusercontent.com/59397159/219037653-3cf8eda8-fd69-4764-a856-8c775460b0d0.png)
![Screenshot from 2023-02-15 14-13-36](https://user-images.githubusercontent.com/59397159/219037657-d7f8db56-b5d0-433e-8807-70e03710d7bd.png)
![Screenshot from 2023-02-15 14-13-26](https://user-images.githubusercontent.com/59397159/219037662-7e15fc16-0bae-4332-8e12-c4fea70761ba.png)
![Screenshot from 2023-02-15 14-13-15](https://user-images.githubusercontent.com/59397159/219037665-c8c40b07-76e1-4fcf-a22b-6eba764d8282.png)

### LICENSE
- [ ] Let's kindly add the license to the readme as the link is currently broken.


### UPDATING HOW USERS CAN HAVE THE PROJECT RUNNING ON THEIR MACHINE
- [ ] Please, kindly update these sections to as follows in order to give a descriptive way users can have your project run locally on their machine below:


```
### Prerequisites

In order to run this project you need:
- vscode.
- git.
- set up an index.html document.

### Setup

Clone this repository to your desired folder:

- Navigate to the directory where you want clone this project in your computer

`$ cd Desktop/`
`$ git clone https://github.com/Jawad-Nazari/Hello-Microverse.git`


### Install

Install this project with this command:

`$ npm install`


### Usage

To run the project, execute the following command by opening the vscode with the command `code .`


you@you-HP-LaptopName:~/Desktop/Hello-Microverse$ code .`
```

2023-02-16 08:31 UTC, Jawad-Nazari commented on index.html
Hi @zieeco ,

I appreciate the time you have spent reviewing my code and providing me with the nice descriptive answers and advice.

I just made the changes you suggested, and I would appreciate it if you could review them. 

Thanks,
Jawad

2023-02-17 10:08 UTC, aamirkhan2478 requested changes
Hi @Jawad-Nazari , 

![](https://media4.giphy.com/media/CoND5j6Bn1QZUgm1xX/giphy.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ No linter errors.
✔️ Nice one setting up the Hello Microverse Project. 
✔️ Descriptive PR. 

 ## Required Changes ♻️

- [ ] Please fix all requirements which are mentioned by the previous reviewer. :point_up: 
- [ ]  You just fix the PR tile and PR description but you didn't fix the README file kindly fix all requirements as mentioned by the previous reviewer. :point_up: 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 13:21 UTC, MeqdamAlqudah reviewed
Hi @Jawad-Nazari , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't contain any commits since the last review please do the changes required by the last reviewer.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-17 15:00 UTC, Jawad-Nazari commented
Hi @MeqdamAlqudah ,

Thanks for your time , I'm sorry. I have just noticed that I have brought the required changes in the main branch instead of feature-branch.
Now, I have added the necessary changes to the feature-branch so I hope this time my PR be accepted.

2023-02-17 15:01 UTC, GedeonTS approved these changes
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @Jawad-Nazari ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- No linter errors :+1: 
- Good use of gitignore :+1: 
- Nice README file :+1: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 15:36 UTC, merged

2023-02-21 15:38 UTC, Jawad-Nazari commented
Hi @GedeonTS ,

Thanks for your time and for reviewing my code. Appreciate for Approval. 🙏